index:
    path: /
    controller: App\Controller\HomeController::index

dynamic_pages:
    path: /{token}/
    controller: App\Controller\PageController::dynamic_pages
    requirements:
            token: .+