index:
    path: /
    controller: App\Controller\PageController::index

mail_callback:
    path: /mail/callback/
    methods: POST
    controller: App\Controller\MailController::callback

#special_offers:
#    path: /import/special_offers/
#    controller: App\Controller\ImportController::special_offers
#clear_content:
#    path: /import/clear_content/
#    controller: App\Controller\ImportController::clearContent
#change_headers:
#    path: /import/change_headers/
#    controller: App\Controller\ImportController::changeHeaders

dynamic_pages:
    path: /{token}/
    controller: App\Controller\PageController::dynamic_pages
    requirements:
            token: .+